### PR TITLE
fix: update Swagger UI (Static)

### PR DESCRIPTION
**Pull request by ruphy**
Signed-off-by: Riccardo Iaconelli <riccardo.iaconelli@qredo.com>

### CODE REVIEW

**Review by smihaylov — APPROVED** [review]

**Comment by pjfanning** [comment]
Thanks for the change and getting it merged. It still seems that the swagger ui on https://milagro.apache.org/ is still using old code and the problems that brings.

**Comment by ruphy** [comment]
thanks @pjfanning, yes, I just realised this needs to be merged over to the `asfsite` branch in order for the release to be deployed. @kealan @smihaylov could you do this for me?

**Comment by ruphy** [comment]
@pjfanning #39 should have fixed this, I tested and could no longer reproduce the bug. Can you confirm this?

**Comment by pjfanning** [comment]
Thanks @ruphy - that looks good now. ASF Infrastructure had removed access to the page yesterday but it is back now and seems XSS free.

**Pull request merged**
